package com.molar;

import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.zip.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.*;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;
import org.springframework.data.jpa.repository.*;
import org.springframework.web.servlet.config.annotation.*;
import org.springframework.web.servlet.HandlerInterceptor;
import org.springframework.scheduling.annotation.*;
import jakarta.servlet.http.*;
import java.io.*;
import jakarta.persistence.*;

@SpringBootApplication
@EnableScheduling
public class MolarApplication {
  public static void main(String[] args) throws Exception { String root=System.getenv().getOrDefault("APPDATA",Path.of(System.getProperty("user.home"),"AppData","Roaming").toString()); Files.createDirectories(Path.of(root,"Molar","data")); Files.createDirectories(Path.of(root,"Molar","files")); Files.createDirectories(Path.of(root,"Molar","backups")); SpringApplication.run(MolarApplication.class, args); }
  @Bean PasswordEncoder passwordEncoder() { return new BCryptPasswordEncoder(); }
  @Bean CommandLineRunner directories(@Value("${molar.files-dir}") String files, @Value("${molar.backups-dir}") String backups) {
    return args -> { Files.createDirectories(Path.of(files)); Files.createDirectories(Path.of(backups)); };
  }
  @Bean WebMvcConfigurer apiSecurity(AppSessionRepository sessions, UserRepository users) {
    return new WebMvcConfigurer() { @Override public void addInterceptors(InterceptorRegistry registry) { registry.addInterceptor(new HandlerInterceptor() { @Override public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception { String path=request.getRequestURI(); if(!path.startsWith("/api/") || path.equals("/api/health") || path.equals("/api/setup/status") || path.equals("/api/setup") || path.equals("/api/login")) return true; String header=request.getHeader("Authorization"); String token=header!=null&&header.startsWith("Bearer ")?header.substring(7):null; AppSession session=token==null?null:sessions.findByToken(token).orElse(null); if(session==null||session.expiresAt==null||Instant.parse(session.expiresAt).isBefore(Instant.now())) { response.sendError(401,"Sesión vencida o inválida"); return false; } AppUser user=users.findById(session.userId).orElse(null); if(user==null||!user.active){response.sendError(403,"El usuario está desactivado");return false;} if((path.equals("/api/users")||path.startsWith("/api/users/")||path.startsWith("/api/backups"))&&user.role!=Role.ADMIN){response.sendError(403,"Se requieren permisos de administrador");return false;} if(request.getMethod().equals("DELETE")&&user.role==Role.ASSISTANT){response.sendError(403,"El asistente no puede eliminar pacientes");return false;} request.setAttribute("molarUser",user); return true; } }); } };
  }
}

enum Role { OWNER, ADMIN, ODONTOLOGIST, ASSISTANT }
enum AppointmentStatus { PENDING, CONFIRMED, ATTENDED, CANCELLED, ABSENT }

@Entity @Table(name="app_user") class AppUser { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(unique=true) String username; String passwordHash; String displayName; @Enumerated(EnumType.STRING) Role role; String createdAt; boolean active=true; String disabledAt; String disabledReason; String disabledBy; public Long getId(){return id;} public String getUsername(){return username;} public String getDisplayName(){return displayName;} public Role getRole(){return role;} }
@Entity class Patient { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; String firstName; String lastName; String dni; String birthDate; String phone; String email; String address; String insurance; String emergencyContact; String allergies; String medicalHistory; String regularMedication; String notes; boolean active=true; String createdAt; String updatedAt; public Long getId(){return id;} public String getFirstName(){return firstName;} public String getLastName(){return lastName;} public String getDni(){return dni;} public String getBirthDate(){return birthDate;} public String getPhone(){return phone;} public String getEmail(){return email;} public String getAddress(){return address;} public String getInsurance(){return insurance;} public String getEmergencyContact(){return emergencyContact;} public String getAllergies(){return allergies;} public String getMedicalHistory(){return medicalHistory;} public String getRegularMedication(){return regularMedication;} public String getNotes(){return notes;} }
@Entity class ClinicalEntry { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; Long patientId; String entryDate; String reason; String diagnosis; String treatment; String procedure; String teethInvolved; String instructions; String notes; String professional; String createdAt; String updatedAt; public Long getId(){return id;} public Long getPatientId(){return patientId;} public String getEntryDate(){return entryDate;} public String getReason(){return reason;} public String getDiagnosis(){return diagnosis;} public String getTreatment(){return treatment;} public String getProcedure(){return procedure;} public String getTeethInvolved(){return teethInvolved;} public String getInstructions(){return instructions;} public String getNotes(){return notes;} public String getProfessional(){return professional;} }
@Entity class ClinicalIndication { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; Long clinicalEntryId; String medication; String dose; String frequency; String duration; String instructions; String observations; public Long getId(){return id;} public Long getClinicalEntryId(){return clinicalEntryId;} public String getMedication(){return medication;} public String getDose(){return dose;} public String getFrequency(){return frequency;} public String getDuration(){return duration;} public String getInstructions(){return instructions;} public String getObservations(){return observations;} }
@Entity class OdontogramEntry { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; Long patientId; String tooth; String status; String observations; String updatedAt; public Long getId(){return id;} public Long getPatientId(){return patientId;} public String getTooth(){return tooth;} public String getStatus(){return status;} public String getObservations(){return observations;} public String getUpdatedAt(){return updatedAt;} }
@Entity class OdontogramSurface { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; Long odontogramEntryId; String surface; String status; String observations; String updatedAt; public Long getId(){return id;} public String getSurface(){return surface;} public String getStatus(){return status;} public String getObservations(){return observations;} }
@Entity class OdontogramHistory { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; Long patientId; String tooth; String status; String observations; String changedAt; public Long getId(){return id;} public String getTooth(){return tooth;} public String getStatus(){return status;} public String getObservations(){return observations;} public String getChangedAt(){return changedAt;} }
@Entity class Appointment { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; Long patientId; String date; String startTime; String endTime; String reason; @Enumerated(EnumType.STRING) AppointmentStatus status; String notes; String cancellationReason; String updatedAt; public Long getId(){return id;} public Long getPatientId(){return patientId;} public String getDate(){return date;} public String getStartTime(){return startTime;} public String getEndTime(){return endTime;} public String getReason(){return reason;} public AppointmentStatus getStatus(){return status;} public String getNotes(){return notes;} public String getCancellationReason(){return cancellationReason;} public String getUpdatedAt(){return updatedAt;} }
@Entity class AuditLog { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; String username; String action; String entity; String entityId; String createdAt; }
@Entity class AppSession { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(unique=true) String token; Long userId; String createdAt; String expiresAt; public Long getId(){return id;} public String getToken(){return token;} public Long getUserId(){return userId;} public String getExpiresAt(){return expiresAt;} }
@Entity class ClinicalAttachment { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; Long patientId; Long clinicalEntryId; String fileName; @Column(unique=true) String storedName; String contentType; Long size; String uploadedBy; String uploadedAt; public Long getId(){return id;} public Long getPatientId(){return patientId;} public Long getClinicalEntryId(){return clinicalEntryId;} public String getFileName(){return fileName;} public String getContentType(){return contentType;} public Long getSize(){return size;} public String getUploadedBy(){return uploadedBy;} public String getUploadedAt(){return uploadedAt;} }
@Entity class ClinicalTemplate { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(unique=true) String name; String reason; String diagnosis; String procedure; String instructions; String notes; String createdBy; String createdAt; public Long getId(){return id;} public String getName(){return name;} public String getReason(){return reason;} public String getDiagnosis(){return diagnosis;} public String getProcedure(){return procedure;} public String getInstructions(){return instructions;} public String getNotes(){return notes;} }

interface UserRepository extends JpaRepository<AppUser,Long> { Optional<AppUser> findByUsername(String username); }
interface PatientRepository extends JpaRepository<Patient,Long> { List<Patient> findByActiveTrueAndFirstNameContainingIgnoreCaseOrActiveTrueAndLastNameContainingIgnoreCaseOrActiveTrueAndDniContainingIgnoreCaseOrActiveTrueAndPhoneContainingIgnoreCase(String a,String b,String c,String d); }
interface ClinicalEntryRepository extends JpaRepository<ClinicalEntry,Long> { List<ClinicalEntry> findByPatientIdOrderByEntryDateDesc(Long patientId); }
interface ClinicalIndicationRepository extends JpaRepository<ClinicalIndication,Long> { List<ClinicalIndication> findByClinicalEntryId(Long id); }
interface OdontogramEntryRepository extends JpaRepository<OdontogramEntry,Long> { List<OdontogramEntry> findByPatientId(Long patientId); Optional<OdontogramEntry> findByPatientIdAndTooth(Long patientId,String tooth); }
interface OdontogramSurfaceRepository extends JpaRepository<OdontogramSurface,Long> { List<OdontogramSurface> findByOdontogramEntryId(Long id); Optional<OdontogramSurface> findByOdontogramEntryIdAndSurface(Long id,String surface); }
interface OdontogramHistoryRepository extends JpaRepository<OdontogramHistory,Long> { List<OdontogramHistory> findByPatientIdOrderByChangedAtDesc(Long patientId); }
interface AppointmentRepository extends JpaRepository<Appointment,Long> { List<Appointment> findByDateOrderByStartTime(String date); List<Appointment> findByDateBetweenOrderByDateAscStartTime(String from,String to); }
interface AuditLogRepository extends JpaRepository<AuditLog,Long> {}
interface AppSessionRepository extends JpaRepository<AppSession,Long> { Optional<AppSession> findByToken(String token); void deleteByToken(String token); void deleteByUserId(Long userId); }
interface ClinicalAttachmentRepository extends JpaRepository<ClinicalAttachment,Long> { List<ClinicalAttachment> findByPatientIdOrderByUploadedAtDesc(Long patientId); }
interface ClinicalTemplateRepository extends JpaRepository<ClinicalTemplate,Long> { List<ClinicalTemplate> findAllByOrderByNameAsc(); }

@CrossOrigin(origins = "*") @RestController @RequestMapping("/api") class ApiController {
  private final UserRepository users; private final PatientRepository patients; private final ClinicalEntryRepository entries; private final ClinicalIndicationRepository indications; private final OdontogramEntryRepository odontograms; private final OdontogramSurfaceRepository surfaces; private final OdontogramHistoryRepository odontogramHistory; private final AppointmentRepository appointments; private final AuditLogRepository audit; private final AppSessionRepository sessions; private final ClinicalAttachmentRepository attachments; private final ClinicalTemplateRepository templates; private final PasswordEncoder encoder; private final String dataDir; private final String backupsDir; private final String filesDir; private final String controlUrl; private final String tenantId; private final String installationId; private final String installationToken; private final RestClient controlClient;
  ApiController(UserRepository u, PatientRepository p, ClinicalEntryRepository e, ClinicalIndicationRepository i, OdontogramEntryRepository o, OdontogramSurfaceRepository s, OdontogramHistoryRepository h, AppointmentRepository a, AuditLogRepository l, AppSessionRepository ss, ClinicalAttachmentRepository at, ClinicalTemplateRepository t, PasswordEncoder enc, @Value("${spring.datasource.url}") String databaseUrl, @Value("${molar.backups-dir}") String bd, @Value("${molar.files-dir}") String fd, @Value("${molar.control-url}") String cu, @Value("${molar.tenant-id}") String ti, @Value("${molar.installation-id}") String ii, @Value("${molar.installation-token}") String it) { users=u; patients=p; entries=e; indications=i; odontograms=o; surfaces=s; odontogramHistory=h; appointments=a; audit=l; sessions=ss; attachments=at; templates=t; encoder=enc; controlUrl=cu;tenantId=ti;installationId=ii;installationToken=it;controlClient=RestClient.builder().baseUrl(cu).build(); dataDir=System.getenv().getOrDefault("APPDATA",Path.of(System.getProperty("user.home"),"AppData","Roaming").toString())+"/Molar/data"; backupsDir=bd; filesDir=fd; }
  record Login(String username,String password) {} record Setup(String dentistName,String username,String password) {} record NewUser(String displayName,String username,String password,Role role) {}
  @GetMapping("/setup/status") Map<String,Boolean> setup() { return Map.of("configured", users.count()>0); }
  @GetMapping("/health") Map<String,Object> health() { return Map.of("status","ok","database","ok","users",users.count()); }
  @GetMapping("/license/status") Map<String,Object> licenseStatus() { return centralLicense(); }
  @PostMapping("/license/check") Map<String,Object> licenseCheck() { return centralLicense(); }
  @PostMapping("/setup") ResponseEntity<?> setup(@RequestBody Setup s) { if(users.count()>0)return ResponseEntity.status(409).body("Molar ya está configurado"); AppUser u=new AppUser(); u.username=s.username(); u.passwordHash=encoder.encode(s.password()); u.displayName=s.dentistName(); u.role=Role.ADMIN; u.createdAt=now(); users.save(u); return ResponseEntity.ok().build(); }
  @PostMapping("/login") ResponseEntity<?> login(@RequestBody Login l) { var u=users.findByUsername(l.username()).orElse(null); if(u==null||!encoder.matches(l.password(),u.passwordHash)) return ResponseEntity.status(401).body("Usuario o contraseña inválidos"); if(!u.active)return ResponseEntity.status(403).body("El usuario está desactivado"); Map<String,Object> license=centralLicense();if("SUSPENDED".equals(license.get("status"))||"EXPIRED".equals(license.get("status")))return ResponseEntity.status(403).body("La licencia de Molar está suspendida o vencida"); AppSession s=new AppSession();s.token=UUID.randomUUID().toString();s.userId=u.id;s.createdAt=now();s.expiresAt=Instant.now().plus(Duration.ofHours(12)).toString();sessions.save(s);audit("login", "user", u.id, u.username); return ResponseEntity.ok(Map.of("token",s.token,"username",u.username,"displayName",u.displayName,"role",u.role)); }
  @PostMapping("/logout") ResponseEntity<?> logout(HttpServletRequest request) { String header=request.getHeader("Authorization");if(header!=null&&header.startsWith("Bearer "))sessions.deleteByToken(header.substring(7));return ResponseEntity.noContent().build(); }
  @PutMapping("/me/password") ResponseEntity<?> changePassword(@RequestBody Map<String,Object> body, @RequestAttribute("molarUser") AppUser user) { String current=(String)body.get("currentPassword"), next=(String)body.get("newPassword");if(current==null||next==null||next.length()<8||!encoder.matches(current,user.passwordHash))return ResponseEntity.badRequest().body("La contraseña actual no es válida o la nueva es demasiado corta");user.passwordHash=encoder.encode(next);users.save(user);return ResponseEntity.noContent().build(); }
  @GetMapping("/users") List<?> listUsers() { return users.findAll().stream().map(u->Map.of("id",u.id,"username",u.username,"displayName",u.displayName,"role",u.role,"active",u.active,"disabledAt",Objects.requireNonNullElse(u.disabledAt,""),"disabledReason",Objects.requireNonNullElse(u.disabledReason,""))).toList(); }
  @PostMapping("/users") Map<String,Object> createUser(@RequestBody Map<String,Object> body) { AppUser u=new AppUser();u.username=(String)body.get("username");u.displayName=(String)body.get("displayName");String password=(String)body.get("password");Role role=Role.valueOf((String)body.getOrDefault("role","ASSISTANT"));if(u.username==null||u.displayName==null||password==null||password.length()<8||role==Role.OWNER)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Datos inválidos: la contraseña debe tener al menos 8 caracteres y OWNER no se crea localmente");u.passwordHash=encoder.encode(password);u.role=role;u.createdAt=now();u=users.save(u);return Map.of("id",u.id,"username",u.username,"displayName",u.displayName,"role",u.role,"active",u.active); }
  @PutMapping("/users/{id}/disable") ResponseEntity<?> disableUser(@PathVariable Long id,@RequestBody(required=false) Map<String,Object> body,@RequestAttribute("molarUser") AppUser actor) { AppUser user=users.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Usuario no encontrado")); if(user.id.equals(actor.id))return ResponseEntity.badRequest().body("No podés desactivar tu propio usuario"); user.active=false;user.disabledAt=now();user.disabledReason=body==null?null:(String)body.get("reason");user.disabledBy=actor.username;users.save(user);sessions.deleteByUserId(user.id);audit("user.disable","user",user.id,actor.username);return ResponseEntity.noContent().build(); }
  @PutMapping("/users/{id}/enable") ResponseEntity<?> enableUser(@PathVariable Long id,@RequestAttribute("molarUser") AppUser actor) { AppUser user=users.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Usuario no encontrado"));user.active=true;user.disabledAt=null;user.disabledReason=null;user.disabledBy=null;users.save(user);audit("user.enable","user",user.id,actor.username);return ResponseEntity.noContent().build(); }
  @GetMapping("/patients") List<Patient> patients(@RequestParam(defaultValue="") String q) { return q.isBlank()?patients.findAll():patients.findByActiveTrueAndFirstNameContainingIgnoreCaseOrActiveTrueAndLastNameContainingIgnoreCaseOrActiveTrueAndDniContainingIgnoreCaseOrActiveTrueAndPhoneContainingIgnoreCase(q,q,q,q); }
  @PostMapping("/patients") Patient createPatient(@RequestBody Map<String,Object> body) { Patient p=patientFrom(body,new Patient());p.createdAt=now();p.updatedAt=p.createdAt;return patients.save(p); }
  @PutMapping("/patients/{id}") Patient updatePatient(@PathVariable Long id,@RequestBody Map<String,Object> body) { Patient p=patientFrom(body,patients.findById(id).orElseThrow());p.updatedAt=now();return patients.save(p); }
  @DeleteMapping("/patients/{id}") ResponseEntity<?> deletePatient(@PathVariable Long id) { if(!patients.existsById(id))return ResponseEntity.notFound().build();patients.deleteById(id);return ResponseEntity.noContent().build(); }
  @GetMapping("/patients/{id}/history") List<Map<String,Object>> history(@PathVariable Long id) { return entries.findByPatientIdOrderByEntryDateDesc(id).stream().map(this::historyData).toList(); }
  @PostMapping("/patients/{id}/history") Map<String,Object> addHistory(@PathVariable Long id,@RequestBody Map<String,Object> body) { ClinicalEntry e=new ClinicalEntry();e.patientId=id;e.entryDate=(String)body.get("entryDate");e.reason=(String)body.get("reason");e.diagnosis=(String)body.get("diagnosis");e.treatment=(String)body.get("treatment");e.procedure=(String)body.get("procedure");e.teethInvolved=(String)body.get("teethInvolved");e.instructions=(String)body.get("instructions");e.notes=(String)body.get("notes");e.professional=(String)body.get("professional");e.createdAt=now();e.updatedAt=e.createdAt;e=entries.save(e);saveIndications(e,body.get("indications"));return historyData(e); }
  @GetMapping("/patients/{id}/odontogram") Map<String,Object> odontogram(@PathVariable Long id) { Map<String,Object> out=new HashMap<>();out.put("current",odontograms.findByPatientId(id).stream().map(e->{Map<String,Object> x=new HashMap<>();x.put("id",e.id);x.put("tooth",e.tooth);x.put("status",e.status);x.put("observations",e.observations);x.put("surfaces",surfaces.findByOdontogramEntryId(e.id));return x;}).toList());out.put("history",odontogramHistory.findByPatientIdOrderByChangedAtDesc(id));return out; }
  @PutMapping("/patients/{id}/odontogram/{tooth}") Map<String,Object> updateTooth(@PathVariable Long id,@PathVariable String tooth,@RequestBody Map<String,Object> body) { OdontogramEntry e=odontograms.findByPatientIdAndTooth(id,tooth).orElseGet(OdontogramEntry::new);e.patientId=id;e.tooth=tooth;e.status=(String)body.get("status");e.observations=(String)body.get("observations");e.updatedAt=now();e=odontograms.save(e);OdontogramHistory h=new OdontogramHistory();h.patientId=id;h.tooth=tooth;h.status=e.status;h.observations=e.observations;h.changedAt=e.updatedAt;odontogramHistory.save(h);Object raw=body.get("surfaces");if(raw instanceof List<?> list)for(Object item:list){if(item instanceof Map<?,?> m){String name=(String)m.get("surface");OdontogramSurface s=surfaces.findByOdontogramEntryIdAndSurface(e.id,name).orElseGet(OdontogramSurface::new);s.odontogramEntryId=e.id;s.surface=name;s.status=(String)m.get("status");s.observations=(String)m.get("observations");s.updatedAt=now();surfaces.save(s);}}Map<String,Object> out=new HashMap<>();out.put("tooth",e.tooth);out.put("status",e.status);out.put("observations",e.observations);out.put("surfaces",surfaces.findByOdontogramEntryId(e.id));return out; }
  @GetMapping("/appointments") List<Appointment> appointments(@RequestParam(defaultValue="") String date,@RequestParam(defaultValue="") String from,@RequestParam(defaultValue="") String to) { if(!from.isBlank()&&!to.isBlank())return appointments.findByDateBetweenOrderByDateAscStartTime(from,to); return appointments.findByDateOrderByStartTime(date.isBlank()?LocalDate.now().toString():date); }
  @PostMapping("/appointments") ResponseEntity<?> createAppointment(@RequestBody Map<String,Object> body,@RequestAttribute("molarUser") AppUser user) { Appointment a=appointmentFrom(body,null);ensureNoOverlap(a);if(a.status==null)a.status=AppointmentStatus.PENDING;a.updatedAt=now();audit("appointment.create","appointment",a.id,user.username);return ResponseEntity.ok(appointments.save(a)); }
  @PutMapping("/appointments/{id}") ResponseEntity<?> updateAppointment(@PathVariable Long id,@RequestBody Map<String,Object> body,@RequestAttribute("molarUser") AppUser user) { Appointment a=appointmentFrom(body,id);ensureNoOverlap(a);a.updatedAt=now();audit("appointment.update","appointment",id,user.username);return ResponseEntity.ok(appointments.save(a)); }
  @GetMapping("/dashboard") Map<String,Object> dashboard() { return Map.of("patients",patients.count(),"today",appointments.findByDateOrderByStartTime(LocalDate.now().toString()),"upcoming",appointments.findByDateOrderByStartTime(LocalDate.now().plusDays(1).toString())); }
  @GetMapping("/backups") List<?> backups() { try { Files.createDirectories(Path.of(backupsDir)); return Files.list(Path.of(backupsDir)).filter(p->p.getFileName().toString().endsWith(".zip")||p.getFileName().toString().endsWith(".db")).sorted(Comparator.reverseOrder()).map(p->{Map<String,Object> item=new HashMap<>();item.put("name",p.getFileName().toString());try{item.put("size",Files.size(p));item.put("createdAt",Files.getLastModifiedTime(p).toInstant().toString());}catch(Exception ignored){}return item;}).toList(); } catch(Exception e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"No se pudieron listar los backups",e);} }
  @Scheduled(cron="0 0 2 * * *") void automaticBackup() { try { Files.createDirectories(Path.of(backupsDir));Path db=Path.of(dataDir,"molar.db");if(Files.exists(db))Files.copy(db,Path.of(backupsDir,"daily-"+LocalDate.now()+".db"),StandardCopyOption.REPLACE_EXISTING); } catch(Exception ignored) {} }
  @PostMapping("/backups") Map<String,Object> createBackup(@RequestAttribute("molarUser") AppUser user) { try { Files.createDirectories(Path.of(backupsDir)); String name="molar-"+LocalDateTime.now().toString().replace(':','-')+".zip";Path target=Path.of(backupsDir,name);try(ZipOutputStream zip=new ZipOutputStream(Files.newOutputStream(target))){Path db=Path.of(dataDir,"molar.db");if(Files.exists(db)){zip.putNextEntry(new ZipEntry("data/molar.db"));Files.copy(db,zip);zip.closeEntry();}Path files=Path.of(dataDir).getParent().resolve("files");if(Files.exists(files))Files.walk(files).filter(Files::isRegularFile).forEach(file->{try{zip.putNextEntry(new ZipEntry("files/"+files.relativize(file)));Files.copy(file,zip);zip.closeEntry();}catch(IOException ex){throw new UncheckedIOException(ex);}});}audit("backup.create","backup",null,user.username);return Map.of("name",name,"createdAt",now());}catch(Exception e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"No se pudo crear el backup",e);} }
  @PostMapping("/backups/{name}/restore") ResponseEntity<?> restoreBackup(@PathVariable String name,@RequestAttribute("molarUser") AppUser user) { if(name.contains("..")||name.contains("/")||(!name.endsWith(".zip")&&!name.endsWith(".db")))return ResponseEntity.badRequest().body("Backup inválido");try{Path source=Path.of(backupsDir,name);if(!Files.exists(source))return ResponseEntity.notFound().build();if(name.endsWith(".db")){Files.copy(source,Path.of(dataDir,"molar.db"),StandardCopyOption.REPLACE_EXISTING);audit("backup.restore","backup",null,user.username);return ResponseEntity.ok(Map.of("message","Backup restaurado. Reiniciá Molar para cargar todos los datos."));}Path before=Path.of(backupsDir,"before-restore-"+LocalDateTime.now().toString().replace(':','-')+".zip");createBackup(user);try(ZipInputStream zip=new ZipInputStream(Files.newInputStream(source))){ZipEntry entry;while((entry=zip.getNextEntry())!=null){if(entry.isDirectory()||!entry.getName().equals("data/molar.db"))continue;Files.copy(zip,Path.of(dataDir,"molar.db"),StandardCopyOption.REPLACE_EXISTING);}}audit("backup.restore","backup",null,user.username);return ResponseEntity.ok(Map.of("message","Backup restaurado. Reiniciá Molar para cargar todos los datos."));}catch(Exception e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"No se pudo restaurar el backup",e);} }
  @GetMapping("/export") Map<String,Object> exportData() { Map<String,Object> out=new HashMap<>();out.put("exportedAt",now());out.put("patients",patients.findAll());out.put("histories",patients.findAll().stream().map(p->history(p.id)).toList());out.put("odontograms",patients.findAll().stream().map(p->odontogram(p.id)).toList());return out; }
  @GetMapping("/patients/{id}/attachments") List<ClinicalAttachment> listAttachments(@PathVariable Long id) { ensurePatient(id);return attachments.findByPatientIdOrderByUploadedAtDesc(id); }
  @PostMapping("/patients/{id}/attachments") ClinicalAttachment uploadAttachment(@PathVariable Long id,@RequestParam("file") MultipartFile file,@RequestAttribute("molarUser") AppUser user) { ensurePatient(id);if(file.isEmpty()||file.getSize()>25_000_000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"El archivo está vacío o supera los 25 MB");try{Files.createDirectories(Path.of(filesDir));String stored=UUID.randomUUID()+"-"+Path.of(Objects.requireNonNullElse(file.getOriginalFilename(),"archivo")).getFileName();Files.copy(file.getInputStream(),Path.of(filesDir,stored),StandardCopyOption.REPLACE_EXISTING);ClinicalAttachment a=new ClinicalAttachment();a.patientId=id;a.fileName=file.getOriginalFilename();a.storedName=stored;a.contentType=file.getContentType();a.size=file.getSize();a.uploadedBy=user.username;a.uploadedAt=now();return attachments.save(a);}catch(IOException e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"No se pudo guardar el archivo",e);} }
  @GetMapping("/attachments/{id}") ResponseEntity<byte[]> downloadAttachment(@PathVariable Long id) { ClinicalAttachment a=attachments.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));try{return ResponseEntity.ok().contentType(MediaType.parseMediaType(Objects.requireNonNullElse(a.contentType,"application/octet-stream"))).header("Content-Disposition","attachment; filename=\""+a.fileName+"\"").body(Files.readAllBytes(Path.of(filesDir,a.storedName)));}catch(IOException e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Archivo no encontrado",e);} }
  @GetMapping("/templates") List<ClinicalTemplate> templates() { return templates.findAllByOrderByNameAsc(); }
  @PostMapping("/templates") ClinicalTemplate createTemplate(@RequestBody Map<String,Object> body,@RequestAttribute("molarUser") AppUser user) { ClinicalTemplate t=new ClinicalTemplate();t.name=(String)body.get("name");t.reason=(String)body.get("reason");t.diagnosis=(String)body.get("diagnosis");t.procedure=(String)body.get("procedure");t.instructions=(String)body.get("instructions");t.notes=(String)body.get("notes");t.createdBy=user.username;t.createdAt=now();return templates.save(t); }
  private void ensurePatient(Long id){if(!patients.existsById(id))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Paciente no encontrado");}
  private void audit(String action,String entity,Long id,String username){ AuditLog l=new AuditLog();l.action=action;l.entity=entity;l.entityId=String.valueOf(id);l.username=username;l.createdAt=now();audit.save(l); }
  private void ensureNoOverlap(Appointment candidate){if(candidate.status==AppointmentStatus.CANCELLED||candidate.status==AppointmentStatus.ABSENT)return;LocalTime start=LocalTime.parse(candidate.startTime),end=LocalTime.parse(candidate.endTime);for(Appointment other:appointments.findByDateOrderByStartTime(candidate.date)){if(candidate.id!=null&&candidate.id.equals(other.id))continue;if(other.status==AppointmentStatus.CANCELLED||other.status==AppointmentStatus.ABSENT)continue;LocalTime otherStart=LocalTime.parse(other.startTime),otherEnd=LocalTime.parse(other.endTime);if(start.isBefore(otherEnd)&&otherStart.isBefore(end))throw new ResponseStatusException(HttpStatus.CONFLICT,"El turno se superpone con otro existente");}}
  private Patient patientFrom(Map<String,Object> b,Patient p){p.firstName=(String)b.get("firstName");p.lastName=(String)b.get("lastName");p.dni=(String)b.get("dni");p.birthDate=(String)b.get("birthDate");p.phone=(String)b.get("phone");p.email=(String)b.get("email");p.address=(String)b.get("address");p.insurance=(String)b.get("insurance");p.emergencyContact=(String)b.get("emergencyContact");p.allergies=(String)b.get("allergies");p.medicalHistory=(String)b.get("medicalHistory");p.regularMedication=(String)b.get("regularMedication");p.notes=(String)b.get("notes");return p;}
  private Map<String,Object> historyData(ClinicalEntry e){Map<String,Object> m=new HashMap<>();m.put("id",e.id);m.put("patientId",e.patientId);m.put("entryDate",e.entryDate);m.put("reason",e.reason);m.put("diagnosis",e.diagnosis);m.put("treatment",e.treatment);m.put("procedure",e.procedure);m.put("teethInvolved",e.teethInvolved);m.put("instructions",e.instructions);m.put("notes",e.notes);m.put("professional",e.professional);m.put("indications",indications.findByClinicalEntryId(e.id));return m;}
  private void saveIndications(ClinicalEntry e,Object raw){if(raw instanceof List<?> list)for(Object item:list)if(item instanceof Map<?,?> m){ClinicalIndication i=new ClinicalIndication();i.clinicalEntryId=e.id;i.medication=(String)m.get("medication");i.dose=(String)m.get("dose");i.frequency=(String)m.get("frequency");i.duration=(String)m.get("duration");i.instructions=(String)m.get("instructions");i.observations=(String)m.get("observations");if(i.medication!=null&&!i.medication.isBlank())indications.save(i);}}
  private Appointment appointmentFrom(Map<String,Object> body,Long id){String date=(String)body.get("date");String start=(String)body.get("startTime");if(date==null||start==null||LocalDateTime.of(LocalDate.parse(date),LocalTime.parse(start)).isBefore(LocalDateTime.now()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"No se pueden crear o modificar turnos pasados");Appointment a=id==null?new Appointment():appointments.findById(id).orElseThrow();a.id=id;a.patientId=((Number)body.get("patientId")).longValue();a.date=date;a.startTime=start;String end=(String)body.get("endTime");a.endTime=end==null||end.isBlank()?LocalTime.parse(start).plusMinutes(30).toString():end;a.reason=(String)body.get("reason");if(body.get("status")!=null)a.status=AppointmentStatus.valueOf((String)body.get("status"));a.notes=(String)body.get("notes");a.cancellationReason=(String)body.get("cancellationReason");return a;}
  private Map<String,Object> centralLicense(){ if(installationId==null||installationId.isBlank()||installationToken==null||installationToken.isBlank())return Map.of("status","ACTIVE","source","local","configured",false); try { Map<?,?> response=controlClient.post().uri("/api/installations/check").header("Authorization","Bearer "+installationToken).body(Map.of("installationId",installationId,"installedVersion","1.0.0")).retrieve().body(Map.class); Map<String,Object> result=new HashMap<>();if(response!=null)response.forEach((key,value)->result.put(String.valueOf(key),value));result.put("source","central");return result; } catch(RestClientResponseException invalidCredentials) { return Map.of("status","SUSPENDED","source","central","configured",true); } catch(Exception unavailable) { return Map.of("status","ACTIVE","source","offline","configured",true); } }
  private String now(){return Instant.now().toString();}
}
